spring:
  datasource:
    url: jdbc:mysql://localhost:3306/klf?serverTimezone=UTC
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
logging:
  level:
    root: warn
    com.donald: info